import React from "react";
import EnergyConsumptionModule from "./Energy";

export default function HvacPage() {
  return <EnergyConsumptionModule />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
