import React from "react";
import AirCompressor from "./AirCompressor";

export default function AirCompressorPage() {
  return <AirCompressor />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
