import React from "react";
import ChillerModule from "./Chiller";

export default function HvacPage() {
  return <ChillerModule />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
