import React from "react";
import HvacModule from "./Hvac";

export default function HvacPage() {
  return <HvacModule />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
