import React from "react";
import Login from "./Login";

export default function LoginPage() {
  return <Login />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
